name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
        - uses: oven-sh/setup-bun@v2
        - run: bunx jsr publish
